In [14]:
import sys

user_path = os.path.expanduser('~')
sys.path.append('..')

# sys.path.append('/Users/geickelb1/Documents/GitHub/covid-chicago/')
# sys.path.append('/Users/geickelb1/Documents/GitHub/covid-chicago')
# sys.path.append('/Users/geickelb1/Documents/GitHub/covid-chicago/age_model')
# sys.path.append('/Users/geickelb1/Documents/GitHub/covid-chicago/spatial_model/')


import numpy as np
import pandas as pd
import subprocess
import matplotlib.pyplot as plt
import os
import seaborn as sns
import matplotlib as mpl
import matplotlib.dates as mdates
from datetime import date, timedelta
import itertools
from scipy.interpolate import interp1d #for linear least squares fitting
from load_paths import load_box_paths
mpl.rcParams['pdf.fonttype'] = 42
testMode = False

datapath, projectpath, wdir,exe_dir, git_dir = load_box_paths()

In [21]:
df=pd.read_csv(os.path.join(projectpath, 'simulation_output','30032020_extendedModel_age_test3grp','trajectoriesDat.csv'), index_col=0)

In [46]:
df.head()

,time,susceptible_age0to19,exposed_age0to19,detected_age0to19,infected_age0to19,asymptomatic_age0to19,symptomatic_age0to19,hospitalized_age0to19,critical_age0to19,deaths_age0to19,...,symp_cumul_age60to100,symp_det_cumul_age60to100,hosp_cumul_age60to100,hosp_det_cumul_age60to100,crit_cumul_age60to100,crit_det_cumul_age60to100,detected_cumul_age60to100,sample_num,scen_num,Ki
0,0.000000,250,0,4,4,2,2,0,0,0,...,2,2,0,0,0,0,4,0,1,0.000004
1,1.016949,246,4,4,4,2,1,1,0,0,...,2,2,1,1,0,0,4,0,1,0.000004
2,2.033898,244,5,4,5,2,0,2,1,0,...,2,2,1,1,1,1,4,0,1,0.000004
3,3.050847,238,9,4,7,3,1,2,1,0,...,2,2,1,1,1,1,4,0,1,0.000004
4,4.067797,233,10,5,10,5,2,2,1,0,...,2,2,1,1,1,1,4,0,1,0.000004

In [23]:
list(df)

['time',
 'susceptible_age0to19',
 'exposed_age0to19',
 'detected_age0to19',
 'infected_age0to19',
 'asymptomatic_age0to19',
 'symptomatic_age0to19',
 'hospitalized_age0to19',
 'critical_age0to19',
 'deaths_age0to19',
 'recovered_age0to19',
 'asymp_cumul_age0to19',
 'asymp_det_cumul_age0to19',
 'symp_cumul_age0to19',
 'symp_det_cumul_age0to19',
 'hosp_cumul_age0to19',
 'hosp_det_cumul_age0to19',
 'crit_cumul_age0to19',
 'crit_det_cumul_age0to19',
 'detected_cumul_age0to19',
 'susceptible_age20to59',
 'exposed_age20to59',
 'detected_age20to59',
 'infected_age20to59',
 'asymptomatic_age20to59',
 'symptomatic_age20to59',
 'hospitalized_age20to59',
 'critical_age20to59',
 'deaths_age20to59',
 'recovered_age20to59',
 'asymp_cumul_age20to59',
 'asymp_det_cumul_age20to59',
 'symp_cumul_age20to59',
 'symp_det_cumul_age20to59',
 'hosp_cumul_age20to59',
 'hosp_det_cumul_age20to59',
 'crit_cumul_age20to59',
 'crit_det_cumul_age20to59',
 'detected_cumul_age20to59',
 'susceptible_age60to100',
 'exposed_age60to100',
 'detected_age60to100',
 'infected_age60to100',
 'asymptomatic_age60to100',
 'symptomatic_age60to100',
 'hospitalized_age60to100',
 'critical_age60to100',
 'deaths_age60to100',
 'recovered_age60to100',
 'asymp_cumul_age60to100',
 'asymp_det_cumul_age60to100',
 'symp_cumul_age60to100',
 'symp_det_cumul_age60to100',
 'hosp_cumul_age60to100',
 'hosp_det_cumul_age60to100',
 'crit_cumul_age60to100',
 'crit_det_cumul_age60to100',
 'detected_cumul_age60to100',
 'sample_num',
 'scen_num',
 'Ki']

In [27]:
set([x.split('_')[0] for x in list(df) if len(x.split('_'))>1])

{'asymp',
 'asymptomatic',
 'crit',
 'critical',
 'deaths',
 'detected',
 'exposed',
 'hosp',
 'hospitalized',
 'infected',
 'recovered',
 'sample',
 'scen',
 'susceptible',
 'symp',
 'symptomatic'}

In [40]:
['age0to19' in x for x in list(df)]

[False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [45]:
[x in b for b in list(df) for x in ['age0to19', 'age20to59', 'age60to100']]

[False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [ ]:
[x for b in a for x in b]

In [61]:
list(set([x.split('_')[-1] for x in list(df) if len(x.split('_'))>1 and x not in['sample_num', 'scen_num']]))

['age60to100', 'age20to59', 'age0to19']

In [62]:
# ok so list of base names in cols we want to keep:
base_names=set([x.split('_')[0] for x in list(df) if len(x.split('_'))>1])
# list of suffix 
suffix_names= list(set([x.split('_')[-1] for x in list(df) if len(x.split('_'))>1 and x not in['sample_num', 'scen_num']]))

In [51]:
df.columns['age0to19' in x for x in list(df)]

SyntaxError: invalid syntax (<ipython-input-51-9afeffa7a556>, line 1)

In [59]:
bool_list=['age0to19' in x for x in list(df)]
list(df.loc[:,bool_list])

['susceptible_age0to19',
 'exposed_age0to19',
 'detected_age0to19',
 'infected_age0to19',
 'asymptomatic_age0to19',
 'symptomatic_age0to19',
 'hospitalized_age0to19',
 'critical_age0to19',
 'deaths_age0to19',
 'recovered_age0to19',
 'asymp_cumul_age0to19',
 'asymp_det_cumul_age0to19',
 'symp_cumul_age0to19',
 'symp_det_cumul_age0to19',
 'hosp_cumul_age0to19',
 'hosp_det_cumul_age0to19',
 'crit_cumul_age0to19',
 'crit_det_cumul_age0to19',
 'detected_cumul_age0to19']

In [74]:
#bool_list=[y in x for y in suffix_names for x in list(df)]
#y for y in suffix_names
#any(x in str for x in a)

#any(substring in string for substring in substring_list)

#### automated wrangling columns wanted for melt
col_bools= []
for element in list(df):
    col_bools.append(any(substring in element for substring in suffix_names))
#print(len(col_bools), len(list(df)))

61 61

In [75]:
col_bools

[False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False]

In [70]:
#bool_list=[any(y in suffix_names in x for y in suffix_names for x in list(df)]
#any(ext in url_string for ext in extensionsToCheck):
any(y in x for x in list(df))

TypeError: 'in <string>' requires string as left operand, not list

In [ ]:
any(x in list in suffix_names)
#[x for x in a if x in str]

In [66]:
bool_list

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [78]:
# # generating a list of base names in cols we might want to keep:
# base_names=set([x.split('_')[0] for x in list(df) if len(x.split('_'))>1])
# # generating a list of suffix names in cols we might want to keep:
# suffix_names= list(set([x.split('_')[-1] for x in list(df) if len(x.split('_'))>1 and x not in['sample_num', 'scen_num']]))

# #### automated wrangling columns wanted for melt
# col_bools= []
# for element in list(df):
#     col_bools.append(any(substring in element for substring in suffix_names))
# ### melting from wide to long
# pd.melt(df, id_vars=['time'], value_vars=list(df.loc[:,col_bools]), var_name='channels')

           time                   channels  value
0      0.000000       susceptible_age0to19    250
1      1.016949       susceptible_age0to19    246
2      2.033898       susceptible_age0to19    244
3      3.050847       susceptible_age0to19    238
4      4.067797       susceptible_age0to19    233
5      5.084746       susceptible_age0to19    224
6      6.101695       susceptible_age0to19    214
7      7.118644       susceptible_age0to19    208
8      8.135593       susceptible_age0to19    186
9      9.152542       susceptible_age0to19    165
10    10.169492       susceptible_age0to19    137
11    11.186441       susceptible_age0to19    104
12    12.203390       susceptible_age0to19     78
13    13.220339       susceptible_age0to19     62
14    14.237288       susceptible_age0to19     45
15    15.254237       susceptible_age0to19     38
16    16.271186       susceptible_age0to19     28
17    17.288136       susceptible_age0to19     20
18    18.305085       susceptible_age0to19     14
19    19.322034       susceptible_age0to19      9
20    20.338983       susceptible_age0to19      5
21    21.355932       susceptible_age0to19      5
22    22.372881       susceptible_age0to19      4
23    23.389831       susceptible_age0to19      2
24    24.406780       susceptible_age0to19      2
25    25.423729       susceptible_age0to19      1
26    26.440678       susceptible_age0to19      0
27    27.457627       susceptible_age0to19      0
28    28.474576       susceptible_age0to19      0
29    29.491525       susceptible_age0to19      0
...         ...                        ...    ...
3390  30.508475  detected_cumul_age60to100      4
3391  31.525424  detected_cumul_age60to100      4
3392  32.542373  detected_cumul_age60to100      4
3393  33.559322  detected_cumul_age60to100      4
3394  34.576271  detected_cumul_age60to100      4
3395  35.593220  detected_cumul_age60to100      4
3396  36.610169  detected_cumul_age60to100      4
3397  37.627119  detected_cumul_age60to100      4
3398  38.644068  detected_cumul_age60to100      4
3399  39.661017  detected_cumul_age60to100      4
3400  40.677966  detected_cumul_age60to100      4
3401  41.694915  detected_cumul_age60to100      4
3402  42.711864  detected_cumul_age60to100      4
3403  43.728814  detected_cumul_age60to100      4
3404  44.745763  detected_cumul_age60to100      4
3405  45.762712  detected_cumul_age60to100      4
3406  46.779661  detected_cumul_age60to100      4
3407  47.796610  detected_cumul_age60to100      4
3408  48.813559  detected_cumul_age60to100      4
3409  49.830508  detected_cumul_age60to100      4
3410  50.847458  detected_cumul_age60to100      4
3411  51.864407  detected_cumul_age60to100      4
3412  52.881356  detected_cumul_age60to100      4
3413  53.898305  detected_cumul_age60to100      4
3414  54.915254  detected_cumul_age60to100      4
3415  55.932203  detected_cumul_age60to100      4
3416  56.949153  detected_cumul_age60to100      4
3417  57.966102  detected_cumul_age60to100      4
3418  58.983051  detected_cumul_age60to100      4
3419  60.000000  detected_cumul_age60to100      4

[3420 rows x 3 columns]

In [115]:
def melter(df):

    """
    overview: melts columns of the grouped 
    it woulda been fairly straight forward, but i wanted to automate the finding of columns we want to keep so we dont need ot specify which columns have the prefex and suffix, and which we want to keep. 
    it should be all automatic now base_names splits a string into a list based on the "_" delimiter, and takes the first entry, but only if the entry list is longer than 1 and i do that for all column names
    
    suffix_list does same thing but takes the last entry and excludes a few suffixes (sample_num and scen_num). 
    so it does a pretty good job at finding the "channels" (base_names) and the channel groups (suffix_names).   
    i then make a list of booleans that loops over all column names and makes it true if any of the suffix_names match the col name. 
    so the final result is a bool list of all columns we want to pivot.
    
    """
    # generating a list of base names in cols we might want to keep:
    base_names=set([x.split('_')[0] for x in list(df) if len(x.split('_'))>1 and x not in ['scen','sample']])
    # generating a list of suffix names in cols we might want to keep:
    suffix_names= list(set([x.split('_')[-1] for x in list(df) if len(x.split('_'))>1 and x not in['sample_num', 'scen_num']]))


    #### automated wrangling columns wanted for melt
    col_bools= []
    for element in list(df):
        col_bools.append(any(substring in element for substring in suffix_names))
    ### melting from wide to long
    df_melted=pd.melt(df, id_vars=[x for x in list(df) if x not in list(df.loc[:,col_bools])], value_vars=list(df.loc[:,col_bools]), var_name='channels')

    df_melted['base_channel']= df_melted['channels'].apply(lambda x: "_".join(str(x).split('_')[:-1]))
    df_melted['base_group']= df_melted['channels'].apply(lambda x: str(x).split('_')[-1])
    
    return(df_melted)

In [126]:
df_melted= melter(df)
df_melted.head()

,time,sample_num,scen_num,Ki,channels,value,base_channel,base_group
0,0.000000,0,1,0.000004,susceptible_age0to19,250,susceptible,age0to19
1,1.016949,0,1,0.000004,susceptible_age0to19,246,susceptible,age0to19
2,2.033898,0,1,0.000004,susceptible_age0to19,244,susceptible,age0to19
3,3.050847,0,1,0.000004,susceptible_age0to19,238,susceptible,age0to19
4,4.067797,0,1,0.000004,susceptible_age0to19,233,susceptible,age0to19

In [133]:
list(df_melted['base_group'].unique())

['age0to19', 'age20to59', 'age60to100']

In [123]:
#df_melted.pivot_table(index='time',columns='base_channel',values='value')

base_channel,asymp_cumul,asymp_det_cumul,asymptomatic,crit_cumul,crit_det_cumul,critical,deaths,detected,detected_cumul,exposed,hosp_cumul,hosp_det_cumul,hospitalized,infected,recovered,susceptible,symp_cumul,symp_det_cumul,symptomatic
time,,,,,,,,,,,,,,,,,,,
0.000000,2.000000,2.0,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000,4.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,333.333333,2.000000,2.000000,2.000000
1.016949,2.000000,2.0,1.666667,0.000000,0.000000,0.000000,0.000000,4.000000,4.333333,2.666667,1.333333,1.000000,1.333333,4.666667,0.333333,329.666667,3.000000,2.333333,1.666667
2.033898,2.000000,2.0,1.666667,0.666667,0.666667,0.666667,0.000000,4.333333,4.666667,5.333333,2.333333,2.000000,1.666667,5.000000,0.666667,326.333333,4.333333,2.333333,1.000000
3.050847,2.333333,2.0,2.000000,1.000000,1.000000,1.000000,0.000000,4.333333,4.666667,8.666667,2.666667,2.000000,1.666667,6.666667,0.666667,321.333333,5.000000,2.333333,2.000000
4.067797,3.000000,2.0,2.666667,1.333333,1.333333,1.333333,0.000000,5.333333,6.000000,12.000000,4.000000,3.333333,2.333333,9.000000,1.000000,315.333333,7.000000,2.666667,2.666667
5.084746,3.666667,2.0,3.000000,2.000000,1.666667,1.666667,0.000000,5.333333,7.000000,20.000000,6.000000,4.333333,3.333333,10.333333,2.000000,305.000000,9.333333,2.666667,2.333333
6.101695,5.333333,2.0,4.333333,3.333333,2.666667,2.666667,0.000000,6.333333,8.666667,28.333333,7.000000,5.666667,2.666667,13.666667,3.333333,292.000000,12.000000,3.333333,4.000000
7.118644,6.333333,2.0,5.333333,4.666667,3.333333,4.000000,0.000000,7.666667,10.333333,41.333333,8.666667,6.333333,2.666667,19.666667,4.333333,272.000000,15.333333,4.333333,7.666667
8.135593,8.666667,2.0,7.666667,6.333333,4.000000,4.666667,0.000000,9.666667,13.666667,54.666667,12.666667,8.666667,4.333333,28.000000,7.333333,247.333333,23.000000,5.666667,11.333333
9.152542,11.000000,2.0,9.333333,9.333333,5.666667,6.666667,0.000000,15.000000,20.000000,66.666667,20.333333,12.666667,8.333333,43.333333,10.333333,217.000000,33.000000,8.666667,19.000000
10.169492,13.666667,2.0,11.000000,12.666667,8.000000,9.000000,0.000000,19.000000,26.333333,78.666667,29.666667,18.333333,13.333333,59.333333,15.000000,184.333333,45.666667,11.000000,26.000000
11.186441,16.666667,2.0,13.666667,18.333333,11.000000,14.333333,0.000000,26.666667,36.000000,92.000000,42.000000,26.000000,17.666667,75.000000,19.666667,150.666667,62.333333,15.333333,29.333333
12.203390,20.666667,2.0,16.333333,24.000000,15.333333,19.333333,0.000000,39.333333,50.666667,93.666667,55.333333,36.000000,24.000000,88.333333,26.333333,129.000000,81.666667,22.000000,28.666667
13.220339,24.000000,2.0,18.333333,35.666667,22.333333,30.000000,0.000000,49.333333,63.666667,88.000000,72.000000,49.333333,26.666667,100.666667,33.000000,115.666667,102.333333,26.333333,25.666667
14.237288,29.000000,2.0,22.000000,48.333333,32.666667,40.000000,0.000000,55.666667,74.666667,80.333333,82.666667,60.333333,23.666667,111.000000,39.333333,106.666667,118.000000,27.333333,25.333333
15.254237,33.000000,2.0,25.000000,57.000000,39.333333,45.333333,0.000000,60.666667,85.000000,66.666667,94.333333,70.333333,24.333333,121.666667,48.333333,100.666667,135.000000,30.666667,27.000000
16.271186,34.666667,2.0,24.666667,66.666667,48.333333,52.666667,0.000000,68.666667,96.000000,55.333333,109.333333,79.333333,28.333333,130.333333,55.666667,96.000000,151.333333,36.333333,24.666667
17.288136,38.333333,2.0,26.333333,77.666667,58.333333,60.666667,0.333333,79.333333,109.333333,48.333333,121.333333,93.666667,28.666667,134.000000,62.666667,92.000000,166.666667,40.000000,18.333333
18.305085,40.666667,2.0,27.666667,86.666667,65.666667,65.666667,0.333333,82.333333,117.000000,38.000000,130.666667,101.000000,27.666667,140.000000,70.000000,89.000000,178.333333,41.333333,19.000000
19.322034,41.666667,2.0,26.000000,98.000000,74.666667,73.666667,0.666667,86.000000,125.666667,33.000000,142.333333,111.666667,26.000000,138.333333,78.333333,87.000000,189.000000,41.666667,12.666667
20.338983,42.666667,2.0,24.333333,105.666667,81.666667,76.333333,0.666667,84.666667,129.666667,27.666667,147.000000,116.666667,21.666667,136.000000,87.666667,85.333333,192.333333,41.666667,13.666667
21.355932,44.000000,2.0,24.666667,113.666667,89.666667,79.666667,0.666667,84.666667,134.333333,22.333333,152.000000,120.666667,17.000000,133.666667,95.333333,85.333333,198.000000,42.666667,12.333333
22.372881,45.000000,2.0,22.666667,118.666667,93.666667,78.666667,0.666667,83.333333,138.000000,17.333333,156.333333,124.000000,16.000000,128.666667,105.666667,85.000000,201.333333,42.333333,11.333333
23.389831,46.000000,2.0,21.666667,125.333333,99.333333,79.666667,0.666667,79.333333,141.000000,15.333333,161.000000,128.000000,13.333333,122.666667,114.333333,84.333333,205.333333,41.333333,8.000000
24.406780,47.000000,2.0,21.666667,131.666667,105.666667,82.000000,0.666667,78.666667,144.333333,12.666667,165.000000,132.000000,10.666667,119.666667,120.000000,84.333333,209.666667,41.333333,5.333333
25.423729,47.333333,2.0,20.333333,135.333333,108.666667,83.000000,0.666667,77.000000,146.666667,10.333333,167.666667,135.000000,8.000000,116.000000,126.333333,84.000000,211.333333,40.666667,4.666667
26.440678,48.000000,2.0,18.666667,138.000000,111.000000,78.666667,0.666667,72.333333,148.000000,8.000000,170.000000,137.000000,7.333333,109.000000,136.000000,83.666667,212.000000,37.333333,4.333333
27.457627,49.333333,2.0,18.333333,141.000000,114.000000,76.666667,0.666667,68.000000,148.666667,6.333333,170.666667,137.333333,5.000000,104.000000,142.666667,83.666667,212.333333,36.333333,4.000000
28.474576,49.333333,2.0,16.333333,142.333333,115.000000,73.666667,0.666667,64.000000,150.333333,5.000000,172.333333,138.666667,4.333333,97.333333,150.666667,83.666667,212.666667,33.333333,3.000000
29.491525,49.666667,2.0,15.666667,143.666667,116.333333,67.000000,0.666667,58.666667,152.000000,4.333333,174.333333,140.666667,4.333333,88.666667,160.333333,83.333333,214.000000,31.333333,1.666667
30.508475,49.666667,2.0,14.000000,145.000000,117.666667,62.666667,0.666667,55.000000,153.000000,3.666667,175.666667,142.333333,4.000000,81.666667,168.000000,83.333333,213.666667,29.666667,1.000000
31.525424,50.000000,2.0,14.000000,145.666667,118.333333,57.333333,0.666667,50.333333,153.333333,2.666667,176.333333,143.000000,3.666667,76.000000,174.666667,83.333333,214.333333,29.000000,1.000000
32.542373,50.000000,2.0,13.666667,147.333333,120.000000,55.666667,0.666667,47.666667,153.333333,2.000000,176.666667,143.333333,2.333333,73.000000,178.333333,83.333333,214.333333,28.333333,1.333333
33.559322,50.000000,2.0,12.333333,148.000000,120.666667,52.000000,0.666667,44.666667,153.333333,1.333333,177.000000,143.333333,2.000000,67.666667,184.333333,83.333333,213.666667,27.666667,1.333333
34.576271,50.000000,2.0,11.666667,149.000000,121.666667,49.333333,0.666667,42.666667,154.333333,1.333333,177.000000,144.000000,1.000000,63.000000,189.000000,83.333333,213.333333,26.333333,1.000000
35.593220,50.000000,2.0,10.666667,149.000000,121.666667,47.333333,0.666667,41.333333,154.666667,0.666667,177.666667,144.333333,1.666667,60.666667,192.000000,83.333333,213.000000,26.333333,1.000000
36.610169,50.000000,2.0,10.333333,149.666667,122.333333,44.333333,0.666667,38.666667,155.333333,0.666667,178.000000,145.000000,1.333333,56.666667,196.000000,83.333333,213.000000,25.000000,0.666667
37.627119,50.000000,2.0,9.666667,149.666667,122.333333,39.666667,0.666667,34.333333,155.333333,0.666667,178.333333,145.333333,1.333333,51.000000,201.666667,83.333333,212.666667,23.333333,0.333333
38.644068,50.000000,2.0,9.000000,149.666667,122.333333,38.333333,0.666667,32.666667,155.333333,0.666667,178.666667,145.333333,1.333333,48.666667,204.000000,83.333333,212.333333,22.333333,0.000000
39.661017,50.000000,2.0,9.000000,150.000000,122.666667,37.000000,0.666667,32.000000,155.666667,0.666667,178.666667,145.666667,1.000000,47.000000,205.666667,83.333333,212.333333,22.000000,0.000000
40.677966,50.000000,2.0,8.000000,150.333333,123.000000,35.000000,0.666667,30.000000,155.666667,0.666667,178.666667,145.666667,0.666667,43.666667,209.000000,83.333333,211.333333,21.333333,0.000000
41.694915,50.000000,2.0,7.666667,150.333333,123.000000,32.000000,0.666667,27.333333,155.666667,0.666667,178.666667,145.666667,0.666667,40.333333,212.333333,83.333333,211.000000,20.333333,0.000000
42.711864,50.000000,2.0,7.333333,150.666667,123.333333,30.333333,0.666667,25.333333,155.666667,0.666667,178.666667,145.666667,0.333333,38.000000,214.666667,83.333333,210.666667,19.333333,0.000000
43.728814,50.000000,2.0,6.333333,150.666667,123.333333,28.000000,1.000000,24.000000,155.666667,0.666667,178.666667,145.666667,0.333333,34.666667,217.666667,83.333333,209.666667,19.000000,0.000000
44.745763,50.333333,2.0,6.333333,150.666667,123.333333,25.666667,1.000000,21.333333,155.666667,0.333333,178.666667,145.666667,0.000000,32.000000,220.666667,83.333333,209.666667,17.666667,0.000000
45.762712,50.333333,2.0,6.000000,150.666667,123.333333,24.333333,1.000000,20.333333,156.000000,0.000000,179.000000,146.000000,0.333333,30.666667,222.333333,83.333333,209.666667,17.333333,0.000000
46.779661,50.333333,2.0,5.333333,150.666667,123.333333,22.666667,1.000000,18.666667,156.000000,0.000000,179.000000,146.000000,0.333333,28.333333,224.666667,83.333333,209.000000,16.666667,0.000000
47.796610,50.333333,2.0,5.000000,150.666667,123.333333,21.333333,1.000000,17.333333,156.000000,0.000000,179.000000,146.000000,0.000000,26.333333,226.666667,83.333333,208.666667,16.333333,0.000000
48.813559,50.333333,2.0,5.000000,150.666667,123.333333,20.333333,1.000000,16.666667,156.000000,0.000000,179.000000,146.000000,0.000000,25.333333,227.666667,83.333333,208.666667,16.000000,0.000000
49.830508,50.333333,2.0,4.666667,150.666667,123.333333,19.666667,1.000000,16.333333,156.000000,0.000000,179.000000,146.000000,0.000000,24.333333,228.666667,83.333333,208.333333,15.666667,0.000000
50.847458,50.333333,2.0,4.666667,150.666667,123.333333,18.333333,1.000000,15.000000,156.000000,0.000000,179.000000,146.000000,0.000000,23.000000,230.000000,83.333333,208.333333,14.666667,0.000000
51.864407,50.333333,2.0,4.666667,150.666667,123.333333,17.000000,1.000000,13.666667,156.000000,0.000000,179.000000,146.000000,0.000000,21.666667,231.333333,83.333333,208.333333,14.333333,0.000000
52.881356,50.333333,2.0,4.666667,150.666667,123.333333,17.000000,1.000000,13.666667,156.000000,0.000000,179.000000,146.000000,0.000000,21.666667,231.333333,83.333333,208.333333,14.333333,0.000000
53.898305,50.333333,2.0,4.333333,150.666667,123.333333,16.000000,1.000000,13.000000,156.000000,0.000000,179.000000,146.000000,0.000000,20.333333,232.666667,83.333333,208.000000,14.000000,0.000000
54.915254,50.333333,2.0,4.333333,150.666667,123.333333,14.000000,1.000000,11.333333,156.000000,0.000000,179.000000,146.000000,0.000000,18.333333,234.666667,83.333333,208.000000,13.666667,0.000000
55.932203,50.333333,2.0,4.333333,150.666667,123.333333,13.333333,1.000000,11.000000,156.000000,0.000000,179.000000,146.000000,0.000000,17.666667,235.333333,83.333333,208.000000,13.333333,0.000000
56.949153,50.333333,2.0,3.666667,150.666667,123.333333,12.000000,1.000000,9.666667,156.000000,0.000000,179.000000,146.000000,0.000000,15.666667,237.333333,83.333333,207.333333,12.666667,0.000000
57.966102,50.333333,2.0,3.666667,150.666667,123.333333,12.000000,1.000000,9.666667,156.000000,0.000000,179.000000,146.000000,0.000000,15.666667,237.333333,83.333333,207.333333,12.666667,0.000000
58.983051,50.333333,2.0,3.000000,150.666667,123.333333,10.666667,1.000000,8.666667,156.000000,0.000000,179.000000,146.000000,0.000000,13.666667,239.333333,83.333333,206.666667,12.000000,0.000000
60.000000,50.333333,2.0,2.333333,150.666667,123.333333,10.666667,1.000000,8.666667,156.000000,0.000000,179.000000,146.000000,0.000000,13.000000,240.000000,83.333333,206.000000,12.000000,0.000000

In [114]:
df_melted.head() #now want to make a base_channel, and base_group col

,time,sample_num,scen_num,Ki,channels,value,base_group,base_channel
0,0.000000,0,1,0.000004,susceptible_age0to19,250,age0to19,susceptible
1,1.016949,0,1,0.000004,susceptible_age0to19,246,age0to19,susceptible
2,2.033898,0,1,0.000004,susceptible_age0to19,244,age0to19,susceptible
3,3.050847,0,1,0.000004,susceptible_age0to19,238,age0to19,susceptible
4,4.067797,0,1,0.000004,susceptible_age0to19,233,age0to19,susceptible

In [101]:
tester="asymp_det_cumul_age60to100"
tester.split('_')[:-1]

['asymp', 'det', 'cumul']

In [107]:
#df_melted['base_group']= 
#df_melted['base_group']=df_melted.groupby('channels')['channels'].apply(lambda x: "_".join(str(x).split('_')[:-1]))
df_melted['base_group']=df_melted.groupby('channels')['channels'].apply(lambda x: "_".join(str(x).split('_')[:-1]))

AttributeError: 'Series' object has no attribute 'split'

In [111]:
df_melted['base_channel']= df_melted['channels'].apply(lambda x: "_".join(str(x).split('_')[:-1]))
df_melted['base_group']= df_melted['channels'].apply(lambda x: str(x).split('_')[-1])

In [112]:
df_melted

,time,sample_num,scen_num,Ki,channels,value,base_group,base_channel
0,0.000000,0,1,0.000004,susceptible_age0to19,250,age0to19,susceptible
1,1.016949,0,1,0.000004,susceptible_age0to19,246,age0to19,susceptible
2,2.033898,0,1,0.000004,susceptible_age0to19,244,age0to19,susceptible
3,3.050847,0,1,0.000004,susceptible_age0to19,238,age0to19,susceptible
4,4.067797,0,1,0.000004,susceptible_age0to19,233,age0to19,susceptible
5,5.084746,0,1,0.000004,susceptible_age0to19,224,age0to19,susceptible
6,6.101695,0,1,0.000004,susceptible_age0to19,214,age0to19,susceptible
7,7.118644,0,1,0.000004,susceptible_age0to19,208,age0to19,susceptible
8,8.135593,0,1,0.000004,susceptible_age0to19,186,age0to19,susceptible
9,9.152542,0,1,0.000004,susceptible_age0to19,165,age0to19,susceptible
10,10.169492,0,1,0.000004,susceptible_age0to19,137,age0to19,susceptible
11,11.186441,0,1,0.000004,susceptible_age0to19,104,age0to19,susceptible
12,12.203390,0,1,0.000004,susceptible_age0to19,78,age0to19,susceptible
13,13.220339,0,1,0.000004,susceptible_age0to19,62,age0to19,susceptible
14,14.237288,0,1,0.000004,susceptible_age0to19,45,age0to19,susceptible
15,15.254237,0,1,0.000004,susceptible_age0to19,38,age0to19,susceptible
16,16.271186,0,1,0.000004,susceptible_age0to19,28,age0to19,susceptible
17,17.288136,0,1,0.000004,susceptible_age0to19,20,age0to19,susceptible
18,18.305085,0,1,0.000004,susceptible_age0to19,14,age0to19,susceptible
19,19.322034,0,1,0.000004,susceptible_age0to19,9,age0to19,susceptible
20,20.338983,0,1,0.000004,susceptible_age0to19,5,age0to19,susceptible
21,21.355932,0,1,0.000004,susceptible_age0to19,5,age0to19,susceptible
22,22.372881,0,1,0.000004,susceptible_age0to19,4,age0to19,susceptible
23,23.389831,0,1,0.000004,susceptible_age0to19,2,age0to19,susceptible
24,24.406780,0,1,0.000004,susceptible_age0to19,2,age0to19,susceptible
25,25.423729,0,1,0.000004,susceptible_age0to19,1,age0to19,susceptible
26,26.440678,0,1,0.000004,susceptible_age0to19,0,age0to19,susceptible
27,27.457627,0,1,0.000004,susceptible_age0to19,0,age0to19,susceptible
28,28.474576,0,1,0.000004,susceptible_age0to19,0,age0to19,susceptible
29,29.491525,0,1,0.000004,susceptible_age0to19,0,age0to19,susceptible
...,...,...,...,...,...,...,...,...
3390,30.508475,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3391,31.525424,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3392,32.542373,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3393,33.559322,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3394,34.576271,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3395,35.593220,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3396,36.610169,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3397,37.627119,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3398,38.644068,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3399,39.661017,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3400,40.677966,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3401,41.694915,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3402,42.711864,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3403,43.728814,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3404,44.745763,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3405,45.762712,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3406,46.779661,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3407,47.796610,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3408,48.813559,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3409,49.830508,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3410,50.847458,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3411,51.864407,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3412,52.881356,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3413,53.898305,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3414,54.915254,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3415,55.932203,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3416,56.949153,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3417,57.966102,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3418,58.983051,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul
3419,60.000000,0,1,0.000004,detected_cumul_age60to100,4,age60to100,detected_cumul

In [106]:
#df_melted['base_group']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11      NaN
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
       ...
3390    NaN
3391    NaN
3392    NaN
3393    NaN
3394    NaN
3395    NaN
3396    NaN
3397    NaN
3398    NaN
3399    NaN
3400    NaN
3401    NaN
3402    NaN
3403    NaN
3404    NaN
3405    NaN
3406    NaN
3407    NaN
3408    NaN
3409    NaN
3410    NaN
3411    NaN
3412    NaN
3413    NaN
3414    NaN
3415    NaN
3416    NaN
3417    NaN
3418    NaN
3419    NaN
Name: base_group, Length: 3420, dtype: object

In [49]:
['age0to19' in x for x in list(df)]

[False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [12]:
import os
os.getcwd()

'C:\\Users\\garrett\\iCloudDrive\\Documents\\GitHub\\covid-chicago\\age_model'